### ISSUE TITLE
Remove config_installer after launch?

### ISSUE THREAD

**Issue by fauxalgore** [stevector/nerdologues-d8#105]
Over in a blog post about config_installer @stevector wrote that it may not be needed after this site is live in Drupal 8: https://github.com/stevector/stevector_posts/pull/12/commits/32decca3328f4bdddfb22ad3b1c4c2678f9b5c25

This issue can track the potential removal of that install profile.

**Comment by stevector** [comment]
I think this issue may be a solution in search of a problem.

**Comment by fauxalgore** [comment]
agreed
