### ISSUE TITLE
Lightning talk

### ISSUE THREAD

**Issue by fauxalgore** [stevector/nerdologues-d8#113]
@stevector, This past weekend at Twin Cities Drupal Camp I gave an after-hours lightning talk on our CircleCI integration. Here are the slides. I don't know if they will have a future life but it seems wise to preserve a reference to them.
[algore.pdf](https://github.com/stevector/nerdologues-d8/files/338467/algore.pdf)

**Comment by stevector** [comment]
Thanks @fauxalgore. I think we can close this issue.
