### ISSUE TITLE
Generate link to clip mp3

### ISSUE THREAD

**Issue by stevector** [stevector/nerdologues-d8#46]

**Comment by stevector** [comment]
Can't work on this until podcast episodes have mp3s

**Comment by stevector** [comment]
I'm reluctant to use  `hook_entity_bundle_field_info` to add a computed field because of https://www.drupal.org/node/2346347

I could just make a field formatter for the entity reference to the podcast episode. But I also want that field to display as text. And there isn't a UI way I can find to add the same field twice to a view mode with DS. This might be the time to switch to Panelizer. Or I could hijack a different field and write a custom field formatter around it. Maybe start time?

**Comment by stevector** [comment]
Yeah, it's not all that weird to think of the clip mp3 as a rendering of the start time field. @fauxalgore what do you think?

**Comment by fauxalgore** [comment]
I think it makes sense to provide the representation of the clip mp3 as a function of the Start Time integer field on the clip. In my mind, that is preferable to building a computed field on an unstable API.
